export interface Ilan {
  _id?: string;
  baslik: string;
  sirket?: string;
  sehir: string;
  mahalle?: string;
  tarih: string;
  maas?: string;
  yabanci_dil?: string;
  bilgisayar_programi?: string;
}
  
export const beylikduzuMahalleleri = [
  "Adnan Kahveci Mahallesi", 
  "Barış Mahallesi", 
  "Büyükşehir Mahallesi", 
  "Cumhuriyet Mahallesi", 
  "Dereağzı Mahallesi", 
  "Gürpınar Mahallesi", 
  "Kavaklı Mahallesi", 
  "Marmara Mahallesi", 
  "Sahil Mahallesi", 
  "Yakuplu Mahallesi"
];

export default beylikduzuMahalleleri;
export const populerPozisyonlar = [
  "Yazılım Geliştirici",
  "Satış Temsilcisi",
  "Proje Yöneticisi",
  "Muhasebe Uzmanı",
  "İnsan Kaynakları Uzmanı",
  "Sekreter",
  "Pazarlama Uzmanı",
  "Çağrı Merkezi Temsilcisi",
  "Teknik Servis",
  "Şoför",
  "Grafik Tasarımcı",
  "Web Tasarımcı",
  "Sosyal Medya Uzmanı",
  "Dijital Pazarlama Uzmanı",
  "Veri Analisti",
  "Sistem Yöneticisi",
  "Network Uzmanı",
  "Elektrik Mühendisi",
  "Makine Mühendisi",
  "İnşaat Mühendisi",
  "Mimar",
  "Doktor",
  "Hemşire",
  "Eczacı",
  "Öğretmen",
  "Danışman",
  "Depo Görevlisi",
  "Kasiyer",
  "Garson",
  "Aşçı",
  "Temizlik Görevlisi",
  "Güvenlik Görevlisi",
  "Bakım Onarım Elemanı",
  "İş Geliştirme Uzmanı",
  "Satın Alma Uzmanı",
  "Lojistik Uzmanı",
  "Müşteri Temsilcisi",
  "Finans Uzmanı",
  "Halkla İlişkiler Uzmanı",
  "Editör",
  "Yazar",
  "Çevirmen",
  "Video Editörü",
  "Fotoğrafçı",
  "Reklamcı",
  "İç Mimar",
  "Diş Hekimi",
  "Psikolog",
  "Saha Satış Elemanı",
  "Çağrı Merkezi Müdürü",
  "İdari İşler Uzmanı",
  "İK Asistanı",
  "Stajyer",
  "Yönetici Asistanı",
  "Ofis Elemanı",
  "Kurye",
  "Bakıcı",
  "Çocuk Bakıcısı",
  "Yaşlı Bakıcısı",
  "Ev Hizmetlisi",
  "Teknik Ressam",
  "Yazılım Test Uzmanı",
  "Mobil Uygulama Geliştirici",
  "Veritabanı Yöneticisi",
  "SEO Uzmanı",
  "E-Ticaret Uzmanı",
  "Satış Müdürü",
  "Mağaza Müdürü",
  "Banka Memuru",
  "Sigorta Uzmanı",
  "Çağrı Merkezi Operatörü",
  "Saha Elemanı",
  "İşçi",
  "Operatör",
  "Forklift Operatörü",
  "Üretim Elemanı",
  "Montaj Elemanı",
  "Bakım Teknisyeni",
  "Servis Elemanı",
  "Tekniker",
  "Laborant",
  "Ar-Ge Uzmanı",
  "Kalite Kontrol Uzmanı",
  "Planlama Uzmanı",
  "Satış Destek Uzmanı",
  "Pazarlama Müdürü",
  "İş Analisti",
  "Yönetici",
  "Genel Müdür",
  "Bölge Müdürü",
  "Şube Müdürü",
  "Proje Koordinatörü",
  "Eğitim Uzmanı",
  "Eğitmen",
  "Saha Mühendisi",
  "Yazılım Mühendisi",
  "Donanım Mühendisi",
  "Bilgi İşlem Uzmanı",
  "Sistem Destek Uzmanı",
  "Çağrı Merkezi Süpervizörü"
];
export const yabanciDiller = [
  "İngilizce",
  "Almanca",
  "Fransızca",
  "Rusça",
  "Arapça",
  "İspanyolca",
  "İtalyanca"
];
export const bilgisayarProgramlari = [
  "Microsoft Office",
  "Excel",
  "Word",
  "PowerPoint",
  "Photoshop",
  "AutoCAD",
  "SolidWorks",
  "Logo",
  "SAP",
  "Canva",
  "CorelDRAW",
  "Premiere Pro",
  "Illustrator",
  "Unity",
  "Visual Studio",
  "NetCAD"
];